(G-code generated by FlatCAM Evo vUnstable - Version Date: 2023/6/31)

(Name: KiCad-PTH.drl_cnc)
(Type: G-code from Excellon)
(Units: MM)

(Created on Tuesday, 01 September 2026 at 07:55)

(This preprocessor has a special sequence when doing a toolchange.)
(Compatible with MACH3.)


(TOOLS DIAMETER: )
(Tool: 1 -> Dia: 0.8)
(Tool: 2 -> Dia: 1.0)

(FEEDRATE Z: )
(Tool: 1 -> Feedrate: 300)
(Tool: 2 -> Feedrate: 300)

(FEEDRATE RAPIDS: )
(Tool: 1 -> Feedrate Rapids: 1500)
(Tool: 2 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 1 -> Z_Cut: -1.8)
(Tool: 2 -> Z_Cut: -1.8)

(Tools Offset: )
(Tool: 1 -> Offset Z: 0.0)
(Tool: 2 -> Offset Z: 0.0)

(Z_MOVE: )
(Tool: 1 -> Z_Move: 2.0)
(Tool: 2 -> Z_Move: 2.0)

(Z Toolchange: 15 mm)
(X,Y Toolchange: 0.0000, 0.0000 mm)
(Z Start: None mm)
(Z End: 15 mm)
(X,Y End: None mm)
(Steps per circle: 16)
(Preprocessor Excellon: Toolchange_Manual)

(X range:    4.8200 ...   41.0000  mm)
(Y range:   -1.7600 ...   21.9000  mm)

(Spindle Speed: 2000 RPM)
G21
G90
G17
G94


G01 F300.00

M5
G00 Z15.0000
T1 
G00 X0.0000 Y0.0000 
(MSG, Change to Tool Dia = 0.8000 ||| Total drills for tool T1 = 16)
M0
G01 Z0
(MSG, Adjust the tool T1 to touch the material and then tighten it slightly.)
M0
G00 Z15.0000
(MSG, Now the tool can be tightened more securely.)
M0
(MSG, Drilling with Tool Dia = 0.8000 ||| Total drills for tool T1 = 16)

G01 F300.00
M03 S2000
G00 X5.2200 Y-1.3600
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X7.7600 Y-1.3600
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X10.3000 Y-1.3600
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X12.8400 Y-1.3600
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X15.3800 Y-1.3600
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X17.9200 Y-1.3600
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X20.4600 Y-1.3600
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X23.0000 Y-1.3600
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X23.0000 Y21.5000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X20.4600 Y21.5000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X17.9200 Y21.5000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X15.3800 Y21.5000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X12.8400 Y21.5000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X10.3000 Y21.5000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X7.7600 Y21.5000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X5.2200 Y21.5000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G01 F300.00

M5
G00 Z15.0000
T2 
G00 X0.0000 Y0.0000 
(MSG, Change to Tool Dia = 1.0000 ||| Total drills for tool T2 = 5)
M0
G01 Z0
(MSG, Adjust the tool T2 to touch the material and then tighten it slightly.)
M0
G00 Z15.0000
(MSG, Now the tool can be tightened more securely.)
M0
(MSG, Drilling with Tool Dia = 1.0000 ||| Total drills for tool T2 = 5)

G01 F300.00
M03 S2000
G00 X40.5000 Y4.5450
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X40.5000 Y7.0850
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X40.5000 Y9.6250
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X40.5000 Y12.1650
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X40.5000 Y14.7050
G01 Z-1.8000
G01 Z0
G00 Z2.0000
M05
G00 Z15.00


