M48
; DRILL file {KiCad 7.0.9} date Thu Nov 14 22:05:49 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-14T22:05:49+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.250
%
G90
G05
T1
X58.62Y72.99
X58.62Y20.99
X83.62Y72.99
X83.62Y20.99
T0
M30
